In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split

In [2]:
df = pd.read_csv("../data/processed_telco_churn.csv")

In [3]:
df.head()

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,OnlineSecurity,OnlineBackup,DeviceProtection,...,MonthlyCharges,TotalCharges,Churn,InternetService_Fiber optic,InternetService_No,Contract_One year,Contract_Two year,PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check
0,0,0,1,0,1,0,0,0,1,0,...,29.85,29.85,0,False,False,False,False,False,True,False
1,1,0,0,0,34,1,0,1,0,1,...,56.95,1889.50,0,False,False,True,False,False,False,True
2,1,0,0,0,2,1,0,1,1,0,...,53.85,108.15,1,False,False,False,False,False,False,True
3,1,0,0,0,45,0,0,1,0,1,...,42.30,1840.75,0,False,False,True,False,False,False,False
4,0,0,0,0,2,1,0,0,0,0,...,70.70,151.65,1,True,False,False,False,False,True,False

In [4]:
X = df.drop("Churn", axis=1)

y = df["Churn"]

In [5]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y, 
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [6]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, classification_report
results = []

In [7]:
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

lr = LogisticRegression(
    random_state=42,
    class_weight="balanced",
)

lr.fit(X_train_scaled, y_train)


pred_lr = lr.predict(X_test_scaled)
accuracy_score(y_test, pred_lr)

from sklearn.metrics import confusion_matrix

pred_lr = lr.predict(X_test_scaled)

print(confusion_matrix(y_test, pred_lr))
print(classification_report(y_test, pred_lr))

results.append({
    "Model": "Logistic Regression",
    "Accuracy": accuracy_score(y_test, pred_lr),
    "Precision": precision_score(y_test, pred_lr),
    "Recall": recall_score(y_test, pred_lr),
    "F1 Score": f1_score(y_test, pred_lr)
})

[[724 309]
 [ 76 298]]
              precision    recall  f1-score   support

           0       0.91      0.70      0.79      1033
           1       0.49      0.80      0.61       374

    accuracy                           0.73      1407
   macro avg       0.70      0.75      0.70      1407
weighted avg       0.79      0.73      0.74      1407

In [8]:
from sklearn.tree import DecisionTreeClassifier

dt = DecisionTreeClassifier(random_state=42, class_weight="balanced")

dt.fit(X_train, y_train)

pred_dt = dt.predict(X_test)
accuracy_score(y_test, pred_dt)

results.append({
    "Model": "Decision Tree",
    "Accuracy": accuracy_score(y_test, pred_dt),
    "Precision": precision_score(y_test, pred_dt),
    "Recall": recall_score(y_test, pred_dt),
    "F1 Score": f1_score(y_test, pred_dt)
})

In [9]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(random_state=42, class_weight="balanced")

rf.fit(X_train, y_train)

pred_rf = rf.predict(X_test)
accuracy_score(y_test, pred_rf)

results.append({
    "Model": "Random Forest",
    "Accuracy": accuracy_score(y_test, pred_rf),
    "Precision": precision_score(y_test, pred_rf),
    "Recall": recall_score(y_test, pred_rf),
    "F1 Score": f1_score(y_test, pred_rf)
})

In [10]:
from sklearn.ensemble import GradientBoostingClassifier

gb = GradientBoostingClassifier(random_state=42)

gb.fit(X_train, y_train)

pred_gb = gb.predict(X_test)

accuracy_score(y_test, pred_gb)

results.append({
    "Model": "Gradient Boosting",
    "Accuracy": accuracy_score(y_test, pred_gb),
    "Precision": precision_score(y_test, pred_gb),
    "Recall": recall_score(y_test, pred_gb),
    "F1 Score": f1_score(y_test, pred_gb)
})

In [11]:
from xgboost import XGBClassifier

xgb = XGBClassifier(
    random_state=42,
    eval_metric="logloss"
)

xgb.fit(X_train, y_train)

pred_xgb = xgb.predict(X_test)

accuracy_score(y_test, pred_xgb)

results.append({
    "Model": "XGBoost",
    "Accuracy": accuracy_score(y_test, pred_xgb),
    "Precision": precision_score(y_test, pred_xgb),
    "Recall": recall_score(y_test, pred_xgb),
    "F1 Score": f1_score(y_test, pred_xgb)
})

In [12]:
results_df = pd.DataFrame(results)
results_df.sort_values(
    by="Accuracy",
    ascending=False
)

                 Model  Accuracy  Precision    Recall  F1 Score
3    Gradient Boosting  0.795309   0.637821  0.532086  0.580175
4              XGBoost  0.771144   0.576023  0.526738  0.550279
2        Random Forest  0.761194   0.542222  0.652406  0.592233
1        Decision Tree  0.727079   0.486842  0.494652  0.490716
0  Logistic Regression  0.726368   0.490939  0.796791  0.607543